name: Unit Test

on:
  pull_request:
    paths:
      - 'web/**'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.0.0

    - name: Run tests with Gradle
      run: ./gradlew test
      
